# Run with: `docker-compose up -d --env-file .my_env`
services:
  backend:
    image: form-filler-backend
    build: .
    #image: "${FF_IMAGE_URL}"
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      UNOSERVER_PORT: ${UNOSERVER_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_SECRET: ${BACKEND_SECRET}
