# Run with: `docker-compose up -d --env-file .my_env`
services:
  gotenberg:
    image: gotenberg/gotenberg:7
    command:
      - "gotenberg"
      - "--pdfengines-engines=uno-pdfengine"
  backend:
    image: "${FF_IMAGE_URL}"
    ports:
      - "8080:8080"
    depends_on:
      - gotenberg
    environment:
      GOTENBERG_API: http://gotenberg:3000/forms/libreoffice/convert
      GOTENBERG_HEALTH: http://gotenberg:3000/health
      DATABASE_URL: ${DATABASE_URL}
      UNOSERVER_PORT: ${UNOSERVER_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
